export const xp = [
  {
    company: 'CoStar Group, Inc.',
    title: 'Associate Software Engineer',
    imagePath: '/experience/costar_logo.png',
    altImageText: 'CoStar Group logo',
    startDate: 'June 2021',
    endDate: 'Present',
    status: 'Full-time',
    location: 'Richmond, VA',
    description: [
      `Created and debugged features for an internal case management software that increased customer support workflows and response time by 40 percent`,
      `Wrote end-to-end tests in Cypress and Typescript to detect regressions in pipelines`,
      `Integrated Stripe API into a customer portal to accept card and bank payments for previously paid-by-mail invoices`,
      `Maintained an in-house React component library`,
    ],
  },
  {
    company: 'Tahzoo',
    title: 'Associate Developer',
    imagePath: '/experience/tahzoo_logo.png',
    altImageText: 'Tahzoo logo',
    startDate: 'August 2020',
    endDate: 'June 2021',
    status: 'Full-time',
    location: 'Richmond, VA',
    description: [
      `Developed an e-commerce microservice in Node.js that wraps an external GraphQL Magento service handling inventory
      and customer cart interactions`,
      `Wrote a microservice in Node.js that locates resellers for ACER hardware utilizing Google Maps API and DynamoDB`,
      `Engineered a cron job in C# that queries an external web service and parses the XML response to be stored in Redis`,
      `Managed interns learning technologies such as .NET, React, and SDL Tridion CMS`,
    ],
  },
  {
    company: 'Tahzoo',
    title: 'Technical Intern',
    imagePath: '/experience/tahzoo_logo.png',
    altImageText: 'Tahzoo logo',
    startDate: 'December 2020',
    endDate: 'August 2020',
    status: 'Part-time',
    location: 'Richmond, VA',
    description: [
      `Delivered a proof-of-concept for migrating two AWS RDS instances using Python to generate csv files for MSSQL
      replication`,
      `Created an internal social media application in React`,
    ],
  },
  {
    company: 'Virginia Commonwealth University',
    title: 'Student',
    imagePath: '/experience/vcu.png',
    altImageText: 'Virginia Commonwealth University logo',
    startDate: 'August 2016',
    endDate: 'May 2021',
    status: 'Full-time',
    location: 'Richmond, VA',
    description: [`Bachelor of Science in Computer Science`, `Minor in Mathematics`],
  },
];
